Add AP configuration still not working.

diff --git a/host/docker/buildroot/overlays/ap/sbin/set_ssid_ap b/host/docker/buildroot/overlays/ap/sbin/set_ssid_ap
--- a/host/docker/buildroot/overlays/ap/sbin/set_ssid_ap
+++ b/host/docker/buildroot/overlays/ap/sbin/set_ssid_ap
@@ -7,7 +7,7 @@
 NC='\[\033[0m\]' # No Color
 RED='\[\033[0;31m\]'
 
-FILE=/etc/hostapd.conf
+FILE=/etc/hostapd/hostapd.conf
 
 # Sanity check
 if [[ ! -f $FILE ]]
@@ -29,8 +29,30 @@ then
   echo "${RED}Error:${NC} $FILE does not contain a ssid field"
   exit 1
 fi
+read -p "wifi password (won't be stored): " -s PASSWORD
+
+# Check password staisfies wpa_passphrase requirement of at least 8 characters
+if [[ `echo $PASSWORD | wc -c` -lt 8 ]]
+then
+  echo "${RED}Error:${NC} Password must contain at least 8 character"
+  exit 1
+fi
 
 # Replace the SSID
-sed -i "s/ssid=(.*)/${SSID}/" $FILE
+sed -i "s/^ssid=.*/ssid=${SSID}/" $FILE
+
+# Hash the password
+KEY=`wpa_passphrase $SSID $PASSWORD | egrep "[^#]psk" | awk -F'=' '{ print $2 }'`
+
+# Check our replacement will work
+grep 'psk=' $FILE > /dev/null
+if [[ $? -ne 0 ]]
+then
+  echo "${RED}Error:${NC} $FILE do not contain a psk field"
+  exit 1
+fi
+
+# Replace the password
+sed -ir s/^wpa_psk=.*/wpa_psk=$KEY/ $FILE
 
 echo "AP configuration to SSID $SSID done"
